config/routes.rb
#---
# Excerpted from "Modern Front-End Development for Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/nrclient for more book information.
#---
Rails.application.routes.draw do
  resources(:favorites)
  resource(:schedule)
  resources(:shopping_carts)
  resources(:ticket_orders)
  resources(:tickets)
  resources(:gigs)
  resources(:concerts)
  resources(:bands)
  resources(:venues)
  devise_for(:users)
  root(to: "schedules#show")
end

app/models/shopping_cart.rb
#---
# Excerpted from "Modern Front-End Development for Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/nrclient for more book information.
#---
# == Schema Information
#
# Table name: shopping_carts
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
class ShoppingCart < ApplicationRecord
  belongs_to :user
end

app/controllers/shopping_carts_controller.rb
#---
# Excerpted from "Modern Front-End Development for Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/nrclient for more book information.
#---
class ShoppingCartsController < ApplicationController
  before_action :set_shopping_cart, only: [:show, :edit, :update, :destroy]

  # GET /shopping_carts
  # GET /shopping_carts.json
  def index
    @shopping_carts = ShoppingCart.all
  end

  # GET /shopping_carts/1
  # GET /shopping_carts/1.json
  def show
  end

  # GET /shopping_carts/new
  def new
    @shopping_cart = ShoppingCart.new
  end

  # GET /shopping_carts/1/edit
  def edit
  end

  # POST /shopping_carts
  # POST /shopping_carts.json
  def create
    @shopping_cart = ShoppingCart.new(shopping_cart_params)

    respond_to do |format|
      if @shopping_cart.save
        format.html do
          redirect_to(
            @shopping_cart,
            notice: "Shopping cart was successfully created."
          )
        end

        format.json do
          render(:show, status: :created, location: @shopping_cart)
        end
      else

        format.html { render(:new) }

        format.json do
          render(json: @shopping_cart.errors, status: :unprocessable_entity)
        end
      end
    end
  end

  # PATCH/PUT /shopping_carts/1
  # PATCH/PUT /shopping_carts/1.json
  def update
    respond_to do |format|
      if @shopping_cart.update(shopping_cart_params)
        format.html do
          redirect_to(
            @shopping_cart,
            notice: "Shopping cart was successfully updated."
          )
        end

        format.json { render(:show, status: :ok, location: @shopping_cart) }
      else
        format.html { render(:edit) }

        format.json do
          render(json: @shopping_cart.errors, status: :unprocessable_entity)
        end
      end
    end
  end

  # DELETE /shopping_carts/1
  # DELETE /shopping_carts/1.json
  def destroy
    @shopping_cart.destroy

    respond_to do |format|
      format.html do
        redirect_to(
          shopping_carts_url,
          notice: "Shopping cart was successfully destroyed."
        )
      end

      format.json { head(:no_content) }
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  private def set_shopping_cart
    @shopping_cart = ShoppingCart.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  private def shopping_cart_params
    params.require(:shopping_cart).permit(:user_id)
  end
end

app/views/shopping_carts/_form.html.erb
<%= simple_form_for(@shopping_cart) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/shopping_carts/edit.html.erb
<h1>Editing Shopping Cart</h1>
<%= render "form", shopping_cart: @shopping_cart %>
<%= link_to "Show", @shopping_cart %> |
<%= link_to "Back", shopping_carts_path %>

app/views/shopping_carts/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Shopping Carts</h1>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @shopping_carts.each do |shopping_cart| %>
      <tr>
        <td><%= shopping_cart.user_id %></td>
        <td><%= link_to "Show", shopping_cart %></td>
        <td><%= link_to "Edit", edit_shopping_cart_path(shopping_cart) %></td>
        <td><%= link_to "Destroy", shopping_cart, method: :delete, data: {confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to "New Shopping Cart", new_shopping_cart_path %>

app/views/shopping_carts/new.html.erb
<h1>New Shopping Cart</h1>
<%= render "form", shopping_cart: @shopping_cart %>
<%= link_to "Back", shopping_carts_path %>

app/views/shopping_carts/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>User:</strong>
  <%= @shopping_cart.user_id %>
</p>
<%= link_to "Edit", edit_shopping_cart_path(@shopping_cart) %> |
<%= link_to "Back", shopping_carts_path %>