config/routes.rb
#---
# Excerpted from "Modern Front-End Development for Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/nrclient for more book information.
#---
Rails.application.routes.draw do
  resources(:favorites)
  resource(:schedule)
  resources(:shopping_carts)
  resources(:ticket_orders)
  resources(:tickets)
  resources(:gigs)
  resources(:concerts)
  resources(:bands)
  resources(:venues)
  devise_for(:users)
  root(to: "schedules#show")
end

app/models/concert.rb
#---
# Excerpted from "Modern Front-End Development for Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/nrclient for more book information.
#---
# == Schema Information
#
# Table name: concerts
#
#  id          :bigint           not null, primary key
#  access      :enum
#  description :text
#  genre_tags  :text
#  ilk         :enum
#  name        :string
#  start_time  :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  venue_id    :bigint           not null
#
class Concert < ApplicationRecord
  belongs_to :venue
  has_many(
    :gigs,
    -> { order(order: :asc) },
    dependent: :destroy,
    inverse_of: :concert
  )

  has_many :bands, through: :gigs
  has_many :tickets, dependent: :destroy

  enum ilk: {concert: "concert", meet_n_greet: "meet_n_greet", battle: "battle"}
  enum access: {general: "general", members: "members", vips: "vips"}

  def start_day
    start_time.to_date
  end

  def duration_minutes
    gigs.map(&:duration_minutes).sum
  end

  def genre_parameters
    genre_tags.split(",").map(&:parameterize).join(",")
  end

  def unsold_ticket_count
    tickets.unsold.count
  end

  def sold_out?
    unsold_ticket_count.zero?
  end

  def sell_out!
    tickets.update_all(status: :purchased, user: User.hoarder)
  end

  def find_ticket_at(row:, number:)
    tickets.find { |ticket| ticket.row == row && ticket.number == number }
  end

  def self.random_purchase_all!(min = 10, max = 30)
    Concert.find_each { |concert| concert.random_purchase!(min, max) }
  end

  def random_purchase!(min = 10, max = 30)
    purchase = rand(min..max)

    purchase.times do
      tickets.unsold.sample.update(status: :purchased, user: User.hoarder)
    end
  end
end

app/controllers/concerts_controller.rb
#---
# Excerpted from "Modern Front-End Development for Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/nrclient for more book information.
#---
class ConcertsController < ApplicationController
  before_action :set_concert, only: [:show, :edit, :update, :destroy]

  # GET /concerts
  # GET /concerts.json
  def index
    @concerts = Concert.all
  end

  # GET /concerts/1
  # GET /concerts/1.json
  def show
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
  end

  # GET /concerts/1/edit
  def edit
  end

  # POST /concerts
  # POST /concerts.json
  def create
    @concert = Concert.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html do
          redirect_to(@concert, notice: "Concert was successfully created.")
        end

        format.json { render(:show, status: :created, location: @concert) }
      else
        format.html { render(:new) }

        format.json do
          render(json: @concert.errors, status: :unprocessable_entity)
        end
      end
    end
  end

  # PATCH/PUT /concerts/1
  # PATCH/PUT /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html do
          render(@concert)
        end

        format.json { render(:show, status: :ok, location: @concert) }
      else
        format.html { render(:edit) }

        format.json do
          render(json: @concert.errors, status: :unprocessable_entity)
        end
      end
    end
  end

  # DELETE /concerts/1
  # DELETE /concerts/1.json
  def destroy
    @concert.destroy

    respond_to do |format|
      format.html do
        redirect_to(concerts_url, notice: "Concert was successfully destroyed.")
      end

      format.json { head(:no_content) }
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  private def set_concert
    @concert = Concert.includes(:tickets).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  private def concert_params
    params.require(:concert).permit(
      :name,
      :description,
      :start_time,
      :venue_id,
      :genre_tags,
      :ilk,
      :access
    )
  end
end

app/views/concerts/_concert.html.erb
<article class="my-4">
  <div class="grid gap-4 grid-cols-5">
    <div class="col-span-1 text-xl">
      <%= concert.start_time.by_example("3:04 PM") %>
    </div>
    <div class="col-span-3">
      <div class="name">
        <div class="text-lg font-bold">
          <%= link_to(concert.name, concert) %>
        </div>
      </div>
      <div class="bands">
        <%= concert.bands.map(&:name).join(", ") %>
      </div>
      <div class="genres">
        <%= concert.genre_tags.split(",").to_sentence %>
      </div>
      <div class="text-gray-500 font-bold">
        <%= concert.venue.name %>
      </div>
    </div>
    <div class="col-span-1 text-xl">
      <% if concert.sold_out? %>
        Sold out
      <% else %>
        <%= pluralize(concert.unsold_ticket_count, "Tickets") %>
        Remaining
      <% end %>
      <br>
      <br>
      <div class="flex">
        <% if current_user %>
          <% if current_user %>
            <%= link_to(
                  "Edit",
                  edit_concert_path(concert),
                  class: SimpleForm.button_class
                ) %>
          <% end %>
          <% if current_user.favorite(concert) %>
            <%= button_to(
                  "Remove Favorite",
                  favorite_path(id: current_user.favorite(concert)),
                  method: "delete",
                  class: SimpleForm.button_class
                ) %>
          <% else %>
            <%= button_to(
                  "Make Favorite",
                  favorites_path(concert_id: concert.id),
                  method: "post",
                  class: SimpleForm.button_class
                ) %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</article>

app/views/concerts/_form.html.erb
<%= simple_form_for(@concert) do |f| %>
  <article class="my-4">
    <div class="grid gap-4 grid-cols-5">
      <div class="col-span-1 text-xl">
        <%= f.input :start_time, label: false %>
      </div>
      <div class="col-span-3">
        <div class="name">
          <div class="text-lg font-bold">
            <%= f.input :name, label: false %>
          </div>
        </div>
        <div class="bands">
          <%= concert.bands.map(&:name).join(", ") %>
        </div>
        <div class="genres">
          <%= f.input :genre_tags, label: false %>
        </div>
        <div class="text-gray-500 font-bold">
          <%= f.association :venue, label: false %>
        </div>
      </div>
      <div class="col-span-1 text-xl my-10">
        <%= f.input :ilk, collection: Concert.ilks, label: false %>
        <%= f.input :access, collection: Concert.accesses, label: false %>
        <%= f.button :submit %>
      </div>
    </div>
  </article>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<% end %>

app/views/concerts/edit.html.erb
<h1>Editing Concert</h1>
<%= render "form", concert: @concert %>
<%= link_to "Show", @concert %> |
<%= link_to "Back", concerts_path %>

app/views/concerts/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Concerts</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start time</th>
      <th>Venue</th>
      <th>Genre tags</th>
      <th>Ilk</th>
      <th>Access</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @concerts.each do |concert| %>
      <tr>
        <td><%= concert.name %></td>
        <td><%= concert.description %></td>
        <td><%= concert.start_time %></td>
        <td><%= concert.venue_id %></td>
        <td><%= concert.genre_tags %></td>
        <td><%= concert.ilk %></td>
        <td><%= concert.access %></td>
        <td><%= link_to "Show", concert %></td>
        <td><%= link_to "Edit", edit_concert_path(concert) %></td>
        <td><%= link_to "Destroy", concert, method: :delete, data: {confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to "New Concert", new_concert_path %>

app/views/concerts/new.html.erb
<h1>New Concert</h1>
<%= render "form", concert: @concert %>
<%= link_to "Back", concerts_path %>

app/views/concerts/show.html.erb
<h1 class="text-4xl font-bold w-auto text-center"><%= @concert.name %></h1>
<h2 class="text-2xl font-semibold">Ticket Info</h2>
<h3 class="text-xl"><%= @concert.ilk %></h3>
<h3 class="text-xl"><%= @concert.access %></h3>
<h3 class="text-xl">
  Start Date: &nbsp;
  <%= @concert.start_time.by_example("Jan 02, 2006") %>
</h3>
<h3 class="text-xl">Venue: <%= @concert.venue.name %></h3>
<h3 class="text-xl">Schedule:</h3>
<% running_time = @concert.start_time %>
<table class="table border border-black w-4/5">
  <thead>
    <tr>
      <th>Time</th>
      <th>Band</th>
      <th>Genres</th>
    </tr>
  </thead>
  <tbody>
    <% @concert.gigs.each do |gig| %>
      <tr>
        <td><%= running_time.by_example("03:04 PM") %></td>
        <td><%= gig.band.name %></td>
        <td><%= gig.band.genre_tags.split(",").join(", ") %></td>
        <% running_time += (gig.duration_minutes * 60) %>
      </tr>
    <% end %>
  </tbody>
</table>
<h2 class="text-2xl font-semibold mt-12">Tickets</h2>
<div class="concert">
  <div class="header">
    <span>Current Tickets Purchased: &nbsp;</span>
    <span>0</span>
  </div>
  <div class="header">
    <span>Current Tickets Cost: &nbsp;</span>
    <span>$0.00</span>
  </div>
  <div class="px-5 py-4 m-2 my-4 w-40 text-center text-white transition-colors duration-150 bg-gray-800 rounded-lg focus:shadow-outline hover:bg-black">
    Clear Tickets
  </div>
  <div>
    <span class="header">How many tickets would you like?</span>
    <span class="select">
      <select>
        <%= @concert.venue.seats_per_row.times do |seat| %>
          <option><%= seat + 1 %></option>
        <% end %>
      </select>
    </span>
  </div>
  <table class="table">
    <tbody>
      <% @concert.venue.rows.times do |row| %>
        <tr>
          <% @concert.venue.seats_per_row.times do |seat| %>
            <% ticket = @concert.find_ticket_at(row: row + 1, number: seat + 1) %>
            <td>
              <%= link_to(ticket_path(ticket.id),
                    method: :patch) do %>
                <div class="<%= ticket.color_for(current_user) %> p-4 m-2 border-black border-4 button hover:bg-blue-300 text-lg">
                  <%= seat + 1 %>
                </div>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="actions">
  <%= link_to("Edit", edit_concert_path(@concert)) %>
  |
  <%= link_to("Back", concerts_path) %>
</div>