config/routes.rb
#---
# Excerpted from "Modern Front-End Development for Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/nrclient for more book information.
#---
Rails.application.routes.draw do
  resources(:favorites)
  resource(:schedule)
  resources(:shopping_carts)
  resources(:ticket_orders)
  resources(:tickets)
  resources(:gigs)
  resources(:concerts)
  resources(:bands)
  resources(:venues)
  devise_for(:users)
  root(to: "schedules#show")
end

app/models/band.rb
#---
# Excerpted from "Modern Front-End Development for Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/nrclient for more book information.
#---
# == Schema Information
#
# Table name: bands
#
#  id          :bigint           not null, primary key
#  description :text
#  genre_tags  :text
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Band < ApplicationRecord
  has_many :gigs, dependent: :destroy
  has_many :concerts, through: :gigs

  def genres
    genre_tags.split(",")
  end
end

app/controllers/bands_controller.rb
#---
# Excerpted from "Modern Front-End Development for Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/nrclient for more book information.
#---
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :edit, :update, :destroy]

  # GET /bands
  # GET /bands.json
  def index
    @bands = Band.all
  end

  # GET /bands/1
  # GET /bands/1.json
  def show
  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands
  # POST /bands.json
  def create
    @band = Band.new(band_params)

    respond_to do |format|
      if @band.save
        format.html do
          redirect_to(@band, notice: "Band was successfully created.")
        end

        format.json { render(:show, status: :created, location: @band) }
      else
        format.html { render(:new) }

        format.json do
          render(json: @band.errors, status: :unprocessable_entity)
        end
      end
    end
  end

  # PATCH/PUT /bands/1
  # PATCH/PUT /bands/1.json
  def update
    respond_to do |format|
      if @band.update(band_params)
        format.html do
          redirect_to(@band, notice: "Band was successfully updated.")
        end

        format.json { render(:show, status: :ok, location: @band) }
      else
        format.html { render(:edit) }

        format.json do
          render(json: @band.errors, status: :unprocessable_entity)
        end
      end
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.json
  def destroy
    @band.destroy

    respond_to do |format|
      format.html do
        redirect_to(bands_url, notice: "Band was successfully destroyed.")
      end

      format.json { head(:no_content) }
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  private def set_band
    @band = Band.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  private def band_params
    params.require(:band).permit(:name, :description, :genre_tags)
  end
end

app/views/bands/_form.html.erb
<%= simple_form_for(@band) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :genre_tags %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<h1>Editing Band</h1>
<%= render "form", band: @band %>
<%= link_to "Show", @band %> |
<%= link_to "Back", bands_path %>

app/views/bands/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Bands</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>genre tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @bands.each do |band| %>
      <tr>
        <td><%= band.name %></td>
        <td><%= band.description %></td>
        <td><%= band.genre_tags %></td>
        <td><%= link_to "Show", band %></td>
        <td><%= link_to "Edit", edit_band_path(band) %></td>
        <td><%= link_to "Destroy", band, method: :delete, data: {confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to "New Band", new_band_path %>

app/views/bands/new.html.erb
<h1>New Band</h1>
<%= render "form", band: @band %>
<%= link_to "Back", bands_path %>

app/views/bands/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @band.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @band.description %>
</p>
<p>
  <strong>genre tags:</strong>
  <%= @band.genre_tags %>
</p>
<%= link_to "Edit", edit_band_path(@band) %> |
<%= link_to "Back", bands_path %>