config/routes.rb
#---
# Excerpted from "Modern Front-End Development for Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/nrclient for more book information.
#---
Rails.application.routes.draw do
  resources(:favorites)
  resource(:schedule)
  resources(:shopping_carts)
  resources(:ticket_orders)
  resources(:tickets)
  resources(:gigs)
  resources(:concerts)
  resources(:bands)
  resources(:venues)
  devise_for(:users)
  root(to: "schedules#show")
end

app/models/ticket_order.rb
#---
# Excerpted from "Modern Front-End Development for Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/nrclient for more book information.
#---
# == Schema Information
#
# Table name: ticket_orders
#
#  id               :bigint           not null, primary key
#  count            :integer          default(0)
#  status           :integer          default(0)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  concert_id       :bigint           not null
#  shopping_cart_id :integer
#
class TicketOrder < ApplicationRecord
  belongs_to :concert
end

app/controllers/ticket_orders_controller.rb
#---
# Excerpted from "Modern Front-End Development for Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/nrclient for more book information.
#---
class TicketOrdersController < ApplicationController
  before_action :set_ticket_order, only: [:show, :edit, :update, :destroy]

  # GET /ticket_orders
  # GET /ticket_orders.json
  def index
    @ticket_orders = TicketOrder.all
  end

  # GET /ticket_orders/1
  # GET /ticket_orders/1.json
  def show
  end

  # GET /ticket_orders/new
  def new
    @ticket_order = TicketOrder.new
  end

  # GET /ticket_orders/1/edit
  def edit
  end

  # POST /ticket_orders
  # POST /ticket_orders.json
  def create
    @ticket_order = TicketOrder.new(ticket_order_params)

    respond_to do |format|
      if @ticket_order.save
        format.html do
          redirect_to(@ticket_order, notice: "Ticket order was successfully created.")
        end

        format.json { render(:show, status: :created, location: @ticket_order) }
      else
        format.html { render(:new) }

        format.json do
          render(json: @ticket_order.errors, status: :unprocessable_entity)
        end
      end
    end
  end

  # PATCH/PUT /ticket_orders/1
  # PATCH/PUT /ticket_orders/1.json
  def update
    respond_to do |format|
      if @ticket_order.update(ticket_order_params)
        format.html do
          redirect_to(@ticket_order, notice: "Ticket order was successfully updated.")
        end

        format.json { render(:show, status: :ok, location: @ticket_order) }
      else
        format.html { render(:edit) }

        format.json do
          render(json: @ticket_order.errors, status: :unprocessable_entity)
        end
      end
    end
  end

  # DELETE /ticket_orders/1
  # DELETE /ticket_orders/1.json
  def destroy
    @ticket_order.destroy

    respond_to do |format|
      format.html do
        redirect_to(
          ticket_orders_url,
          notice: "Ticket order was successfully destroyed."
        )
      end

      format.json { head(:no_content) }
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  private def set_ticket_order
    @ticket_order = TicketOrder.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  private def ticket_order_params
    params.require(:ticket_order).permit(:concert_id)
  end
end

app/views/ticket_orders/_form.html.erb
<%= simple_form_for(@ticket_order) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :concert %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ticket_orders/edit.html.erb
<h1>Editing Ticket Order</h1>
<%= render "form", ticket_order: @ticket_order %>
<%= link_to "Show", @ticket_order %> |
<%= link_to "Back", ticket_orders_path %>

app/views/ticket_orders/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Ticket Orders</h1>
<table>
  <thead>
    <tr>
      <th>Concert</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @ticket_orders.each do |ticket_order| %>
      <tr>
        <td><%= ticket_order.concert_id %></td>
        <td><%= link_to "Show", ticket_order %></td>
        <td><%= link_to "Edit", edit_ticket_order_path(ticket_order) %></td>
        <td><%= link_to "Destroy", ticket_order, method: :delete, data: {confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to "New Ticket Order", new_ticket_order_path %>

app/views/ticket_orders/new.html.erb
<h1>New Ticket Order</h1>
<%= render "form", ticket_order: @ticket_order %>
<%= link_to "Back", ticket_orders_path %>

app/views/ticket_orders/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Concert:</strong>
  <%= @ticket_order.concert_id %>
</p>
<%= link_to "Edit", edit_ticket_order_path(@ticket_order) %> |
<%= link_to "Back", ticket_orders_path %>